### ISSUE TITLE
Шрифты

### ISSUE THREAD

**Issue by cyfive** [omsklug/art#1]
В SVG у меня не отображаются шрифты.

**Comment by sstopkin** [comment]
@cyfive поддержу, отображаются дефолтные шрифты
@linuxmaster идеи есть?

**Comment by cyfive** [comment]
либо в кривые их перегонять, либо интегрировать ручами шрифт в него, это по хорошему, либо просто написать в редми, какой шрифт ставить :)

**Comment by cyfive** [comment]
Добавил readme.md с предупреждением, что надо ставить Driod Sans.
